### PR TITLE
Refactors to substantially improve performance and efficiency

### PR DESCRIPTION
**Pull request by nikito**
The UI originally would make calls to the config and timezone APIs in numerous places every time we loaded a config area or tab. Not only is this unnecessary (SWR dynamically updates on it's own when a change happens so we don't need to keep hammering the APIs), it is also inefficient as it causes the UI to have to do a lot of waiting for information it essentially already has as well as making WAS perform unnecessary work. We instead centralize the calls into a global context that is available to anything that needs it, greatly reducing API calls and improving the UI's responsiveness.

### CODE REVIEW

**Comment by richardklafter** [comment]
Yea, this is not more efficient. We use [SWR](https://swr.vercel.app/) which does client side caching without the congnitive load of keeping that state around. Read the docs there.

**Comment by richardklafter** [comment]
Yea, I think you need https://swr.vercel.app/docs/advanced/understanding#return-previous-data-for-better-ux. Also read isLoading vs isValidating as it will help you understand SWR better. There is 100% a way to handle that case with SWR. On phone so can't code you example right now but if you send troublesome patch I can look tonight.

**Comment by nikito** [comment]
Hmm, or not. @richardklafter I put things back to using SWR instead of context, and the problem I have is whenever I go to click the config tab I get a loading indicator for a split second before it renders, which I can only assume is because it is waiting for data to come back (because I am now loading the data in the config page, not in the app at the global level first). I even tried adding preload to help but no dice. Is this just how SWR is going to work in this case? There's no way I can have these preloaded ahead of time so when we click the configuration tab it doesn't have to do a loading spinner?

**Comment by nikito** [comment]
Yeah that's the issue, I want the SWR stuff loaded before I even go to the config page, so I need something to load it right when the app boots, so I was making the SWR calls in the _app.tsx. Since I was doing that I figured it'd make sense to just pass those along instead of re-calling SWR elsewhere. Is it just better practice to call SWR in there to "preload" them even if I am not using them in that class, so that later on when config calls SWR they will already be cached?

**Comment by richardklafter** [comment]
Need to see your code.

**Comment by richardklafter** [comment]
[Yea, if you just don't ever want to see the loading panel just preload it from root of app.](https://swr.vercel.app/blog/swr-v2.en-US#preloading-data)

**Comment by richardklafter** [comment]
Yea, SWR call has pretty much the same effect as preload and IMO is fine if preload is giving you issue.

**Comment by nikito** [comment]
> > https://swr.vercel.app/blog/swr-v2.en-US#preloading-data preloading data is built in
> 
> Ok that's what I thought, but when I tried preload it told me the URL was invalid, so I changed it to just do a SWR call instead. I'll try preload again and try to figure out what's going wrong, as I agree that seems to be the correct way to do it. :)

Hm I think I get this at compile time because the base path is constructed at runtime, so it complains the url is bad:
`TypeError: Failed to parse URL from undefined/api/config?type=config
    at Object.fetch (node:internal/deps/undici/undici:11372:11)
    at async fetcher (/was-ui/.next/server/chunks/913.js:1:1013) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:405:5)
      at new URL (node:internal/url:637:13)
      at new _Request (node:internal/deps/undici/undici:5055:25)
      at fetch2 (node:internal/deps/undici/undici:9195:25)
      at Object.fetch (node:internal/deps/undici/undici:11370:18)
      at fetch (node:internal/process/pre_execution:242:25)
      at fetcher (/was-ui/.next/server/chunks/913.js:1:1019)
      at preload (file:///was-ui/node_modules/swr/_internal/dist/index.mjs:601:17)
      at App (/was-ui/.next/server/chunks/913.js:1:2484)
      at Wc (/was-ui/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44) {
    input: 'undefined/api/config?type=config',
    code: 'ERR_INVALID_URL'
  }
}`

**Comment by nikito** [comment]
> Yea, SWR call has pretty much the same effect as preload and IMO is fine if preload is giving you issue.

Ok sounds good, thank you for all your help, appreciate the lessons! :)

**Comment by richardklafter** [comment]
Yea, you could muck and make that work but SWR preload is fine IMO.

**Pull request merged**
